### ISSUE TITLE
Change in the UI for uploading data to DBFS

### ISSUE THREAD

**Issue by afelix-95** [MicrosoftLearning/mslearn-databricks#11]
# Module: 01
#### Step: 03-05

Description of issue
The description of how to upload the .csv file to DBFS does not match the options currently available in the UI.

Here is roughly how the steps 03-05 would look like with the changes:

3. Download the [**products.csv**](https://raw.githubusercontent.com/MicrosoftLearning/mslearn-databricks/main/data/products.csv) file from `https://raw.githubusercontent.com/MicrosoftLearning/mslearn-databricks/main/data/products.csv` to your local computer, saving it as **products.csv**. Then, in the **Explore products** notebook, on the **File** menu, select **Add data...** and **DBFS** in the new window.
1. In the **Upload File** tab, note the **DBFS Target Directory** to where the file will be uploaded. Then select the **Files** area, and upload the **products.csv** file you downloaded to your computer.
1. When the file has been uploaded, select **Create Table in Notebook**. This will open a new notebook with sample PySpark codes. Select the first code cell and copy it to the clipboard. You will use it to load the data from the file into a DataFrame.

**Comment by GraemeMalcolm** [comment]
Hmm, I can't repro this - the current steps work for me. as they are.

**Comment by afelix-95** [comment]
For me the **Upload data to DBFS** doesn´t show in the **File** menu. 
Even if I enable the DBFS file browser in the Admin settings, the option that gives me the closest result to what's described in the original steps 03-05 is the **Add data...** option, which is equivalent to selecting **Data Ingestion** in the pane on the left. 
![image](https://github.com/MicrosoftLearning/mslearn-databricks/assets/148110824/bde55b4d-555e-43bf-977f-98107650b957)

**Comment by GraemeMalcolm** [comment]
Weird - here's what I get:
<img width="933" alt="image" src="https://github.com/MicrosoftLearning/mslearn-databricks/assets/11771134/13af70f7-66cb-4159-a6ee-fc93c6029ec5">
 It may be because of the rollout of Unity Catalog. I'll experiment with other options.

**Comment by GraemeMalcolm** [comment]
What happens if you choose **Upload files for volume**?

**Comment by GraemeMalcolm** [comment]
So, I can get your menu if I explicitly attach a Unit Catalog store to the workspace, but by default I only have DBFS storage. You created your workspace using the PowerShell script, right?

**Comment by afelix-95** [comment]
> What happens if you choose **Upload files to volume**? Or **Open DBFS File explorer**?

* For **Upload files to volume** it shows this:

![image](https://github.com/MicrosoftLearning/mslearn-databricks/assets/148110824/0189fa66-f78c-49b8-a786-c985e319ca76)
Here if I create a volume in the workspace's catalog I can upload the file but with no option to have a sample PySpark code to load the data into a dataframe in the notebook.

* For **Open DBFS File explorer**:
![Screenshot 2024-03-21 012745](https://github.com/MicrosoftLearning/mslearn-databricks/assets/148110824/8d0a8b80-0e75-41e9-a719-669460e6c833)
Again, it allows me to upload the file, now in `dbfs:/FileStore` but still with no **Access files from notebooks** or **Create Table in Notebook** option.

**Comment by afelix-95** [comment]
> So, I can get your menu if I explicitly attach a Unity Catalog store to the workspace, but by default I only have DBFS storage. You created your workspace using the PowerShell script, right?

I couldn't directly use the PowerShell script because it has an `available_quota` check with a threshold at 8 cores (line 105):
```shell
if (($available_quota -lt 8) -or ($skuOK -eq 0))
```
So I tried both creating the workspace manually and changing the threshold in the script to 4 cores before running it. Both cases yielded the same results in the end.

**Comment by afelix-95** [comment]
Additionally, I tried doing it through the Skillable lab instance to see if using a different subscription would make any difference, and in there the **Upload data to DBFS** option shows up as expected.

**Comment by GraemeMalcolm** [comment]
Right, so it looks like the Unity rollout has been applied to your tenant/ subscription, but not to mine or the Skillable environment. I'll rewrite the lab so that it works in either case and let you know when it's ready to retest.

**Comment by GraemeMalcolm** [comment]
OK, rewritten - *should* work in both scenarios now!

**Comment by GraemeMalcolm** [comment]
Awesome - many thanks. Closing this issue
