### ISSUE TITLE
Issue in 03-Delta-lake-in-Azure-Databricks

### ISSUE THREAD

**Issue by nishds21** [MicrosoftLearning/mslearn-databricks#14]
# Module: 00
#### Step: 1

Description of issue : Not able to create the table 

Repro steps:

1. Run Step 1 (details mentioned above)
1. Problem occurs when it tries to create a table : spark.sql("CREATE TABLE AdventureWorks.ProductsExternal USING DELTA LOCATION '{0}'".format(delta_table_path))
1. Error message: INVALID_PARAMETER_VALUE: Missing cloud file system scheme.

Additional inputs: Used the cluster specification as mentioned in the lab and also using the premium azure databricks

**Comment by GraemeMalcolm** [comment]
Non-repro for me - I get the following expected output. Is it possible you missed a previous step?

+----------------------------+-------------------------------------------+-------+
|col_name                    |data_type                                  |comment|
+----------------------------+-------------------------------------------+-------+
|ProductID                   |string                                     |NULL   |
|ProductName                 |string                                     |NULL   |
|Category                    |string                                     |NULL   |
|ListPrice                   |string                                     |NULL   |
|                            |                                           |       |
|# Delta Statistics Columns  |                                           |       |
|Column Names                |ProductID, ProductName, Category, ListPrice|       |
|Column Selection Method     |first-32                                   |       |
|                            |                                           |       |
|# Detailed Table Information|                                           |       |
|Catalog                     |spark_catalog                              |       |
|Database                    |AdventureWorks                             |       |
|Table                       |ProductsExternal                           |       |
|Created Time                |Wed Jul 24 16:42:33 UTC 2024               |       |
|Last Access                 |UNKNOWN                                    |       |
|Created By                  |Spark 3.4.1                                |       |
|Type                        |EXTERNAL                                   |       |
|Location                    |dbfs:/delta/products-delta                 |       |
|Provider                    |delta                                      |       |
|Owner                       |root                                       |       |
+----------------------------+-------------------------------------------+-------+
only showing top 20 rows
