### ISSUE TITLE
Can't install Databricks on Azure Portal

### ISSUE THREAD

**Issue by Xuanhoang214** [MicrosoftLearning/mslearn-databricks#17]
# Module: 00
#### Step: 00

Description of issue
After I cloned repo, I run 'setup.ps1'. 
Error 'Could not create a Databricks workspace.
Try using the Azure portal to add one to the msl-6n5hwiu resource group.'
Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
@Xuanhoang214 did you run the repo in the Azure Cloud Shell?

**Comment by madiepev** [comment]
Closing this issue for now due to inactivity. Feel free to recreate one if the problem persists.
