### ISSUE TITLE
LA-07-Use-SQL-warehouse-Create a dashboard task must be reviewed

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/mslearn-databricks#21]
# Module: LA-07-Use-SQL-warehouse
#### Step: All steps

Description of issue:

All steps in the above mentioned task must be reviewed as the portal got changed.

- There is no drop down list in the portal. (step 3)
- Need to create a dataset first (no option to select a query step 4)
- Items mentioned in step 5 need a change. 
In the portal only available options are:
Visualization type: bar
Y column: Category
X columns: Product ID : Count
Group by: Leave blank
![image](https://github.com/user-attachments/assets/b1f38dbd-5b72-468d-840f-1a07e3359cd0)

**Comment by afelix-95** [comment]
Thanks for pointing it out! The instructions are being updated.
