### ISSUE TITLE
DS3_v2 VM does not always deploy

### ISSUE THREAD

**Issue by Jason-Microsoft-MTT** [MicrosoftLearning/mslearn-databricks#28]
All labs containing cluster creation instructions

Description of issue
On occasion, the DS3_v2 instance that is outlined in the instructions fails to deploy as there aren't any instances available. The "new" defaulted version tends to deploy without issue (D4ds_v5). I'm sure there may be others there, but if new versions of VMs are released and the others are phased out, wouldn't it just be wise to have them select the "default" VM?

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
One issue may be the policy constraints in the ILT lab profiles. Can we investigate this and determine impact on cost and policies?

**Comment by theresa-i** [comment]
I'll take a look.

**Comment by TheJamesHerring** [comment]
This is being reviewed by another team member, and I am awaiting their response. Should know soon whether it is a regional issue of the default needs to change.

**Comment by theresa-i** [comment]
@Jason-Microsoft-MTT This change will go live on 9/27/24.  All Databricks labs have been staged to be updated to use the Standard_D4ds_v5 sku on 9/27.

**Comment by theresa-i** [comment]
This has been resolved.   The default sku was changed in each of the Databricks exercises to the Standard_D4ds_v5 sku and the setup script was updated to include this sku and the family it belongs to.
