### ISSUE TITLE
Operation returned an invalid status code 'Forbidden'

### ISSUE THREAD

**Issue by ayoubML** [MicrosoftLearning/mslearn-databricks#3]
[MicrosoftLearning/mslearn-databricks/Allfiles/Labs/03/setup.ps1](https://github.com/MicrosoftLearning/mslearn-databricks/blob/main/Allfiles/Labs/03/setup.ps1)
Lines 130:
   `New-AzRoleAssignment -SignInName $userName -RoleDefinitionName "Owner" -Scope "/subscriptions/$subscriptionId/resourceGroups/$resourceGroupName/providers/Microsoft.Databricks/workspaces/$dbworkspace";
`
Error:
`New-AzRoleAssignment: /home/ayoub/dp-000/Allfiles/Labs/03/setup.ps1:130
Line |
 130 |          New-AzRoleAssignment -SignInName $userName -RoleDefinitionNam …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'Forbidden'`

I have occurred this error when i have running the **setup.ps1** file by following this excercise [Exercise - Use Delta Lake in Azure Databricks](https://docs.microsoft.com/en-us/training/modules/use-delta-lake-azure-databricks/06-exercise-use-delta-lake) in [step 5](https://microsoftlearning.github.io/mslearn-databricks/Instructions/Labs/03-Delta-lake-in-Azure-Databricks.html#provision-an-azure-databricks-workspace)

Any suggestion ?

**Comment by GraemeMalcolm** [comment]
The script assumes you have Admin privileges in the Azure subscription. Without that, it will fail.
