### ISSUE TITLE
Databricks Setup Scripts can fail due to region policy

### ISSUE THREAD

**Issue by IanWhitney** [MicrosoftLearning/mslearn-databricks#4]
# Module: Explore Azure Databricks
#### Step: 05

Description of issue

Note: this occurs in multiple labs, this just happened to be where I first encountered it

If you don't pass in a region as an argument then [the setup script picks a region at random](https://github.com/MicrosoftLearning/mslearn-databricks/blob/50b85dd821521cb11201c0fc6b83f1fc2134e11d/Allfiles/Labs/01/setup.ps1#L72). 

If your organization has a policy in place to limit available regions then this random region can lead to an error like this

```
Resource 'databricksz3o2b57' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Default-Allowed
     | Regions","id":"/providers/Microsoft.Management/managementGroups/OIT/providers/Microsoft.Authorization/policyAssignments/1446524e3b8a437fa42e27b9"},"policyDefinition":{"name":"Allowed locations","id":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c"},"policySetDefinition":{"name":"Default-Allowed Regions","id":"/providers/Microsoft.Management/managementGroups/c7e9abb7-1aa0-47d4-9ff4-49c649b768fd/providers/Microsoft.Authorization/policySetDefinitions/265d7c37-3846-4f4a-ae6b-3af27f6f8227"}}]'.
```

Repro steps:

1. Set a policy that limits allowed regions
1. Run the lab setup script. If it picks a disallowed region you'll get the error.

Suggestions

1. The script allows users to pass in a region name. If a region is provided that region is used. But this is not documented anywhere I could see. I found it by reading the script source. Letting people know that this option exists would help.
2. Instead of picking randomly from all regions, would it be possible to pick randomly from the user's _allowed_ regions?

**Comment by GraemeMalcolm** [comment]
Unfortunately, we can't control organizational policies. The setup assumes you have full administrative control of your subscription.  The script is provided as a convenience. The instructions include the following guidance:

> _"If the script fails due to insufficient quota or permissions, you can try creating an Azure Databricks workspace interactively in the Azure portal._"
