### ISSUE TITLE
setup script requires too many cores

### ISSUE THREAD

**Issue by stvno** [MicrosoftLearning/mslearn-databricks#5]
# Module: 00
#### Step: 05

Description of issue
 I have created a new free azure account to work with the mslearn databrick modules. The standard setup script for Labs 01-04 (I haven't tried 05 yet) fails for not finding any region with sufficient capacity.

Regions will fail while there are zero cores in use:
```
Preparing to deploy. This may take several minutes...
Trying westeurope...
0 of 4 cores in use.
```

Apparently the setup scripts requires at least 8 available cores, while on the free azure subscription there are never more than 4 available *). The solution is to lower the available quota check from 8 to 4:
https://github.com/MicrosoftLearning/mslearn-databricks/blob/main/Allfiles/Labs/01/setup.ps1#L102

The Labs work fine after that change

*) I've tried it at various hours of the day and there were never more than 4 cores available in any region.

**Comment by ChristianRRL** [comment]
@stvno, I've run into the same issues. I am seeing a message like this:

Trying <looping region>...
0 of 4 cores in use.

**Comment by FrankieChoi** [comment]
It works after changing `$available_quota -lt 8` to 4 in https://github.com/MicrosoftLearning/mslearn-databricks/blob/main/setup.ps1#L105

**Comment by YungAleco** [comment]
> # Module: 00
> ## Lab/Demo: 01-04
> ### Task: 00
> #### Step: 05
> Description of issue I have created a new free azure account to work with the mslearn databrick modules. The standard setup script for Labs 01-04 (I haven't tried 05 yet) fails for not finding any region with sufficient capacity.
> 
> Regions will fail while there are zero cores in use:
> 
> ```
> Preparing to deploy. This may take several minutes...
> Trying westeurope...
> 0 of 4 cores in use.
> ```
> 
> Apparently the setup scripts requires at least 8 available cores, while on the free azure subscription there are never more than 4 available *). The solution is to lower the available quota check from 8 to 4: https://github.com/MicrosoftLearning/mslearn-databricks/blob/main/Allfiles/Labs/01/setup.ps1#L102
> 
> The Labs work fine after that change
> 
> *) I've tried it at various hours of the day and there were never more than 4 cores available in any region.

thanks man you saved me.


> There's a single setup script for all exercises, so it must support the max cores needed. The setup assumes you have full administrative control of your subscription. The script is provided as a convenience. The instructions include the following guidance:
> 
> > _"If the script fails due to insufficient quota or permissions, you can try creating an Azure Databricks workspace interactively in the Azure portal._"

i had problemas with that because the resource group for the databricks service is not being create because of script fail.
Changing the cores quote already nailed it
