### ISSUE TITLE
Broken Link in Use Data Lake in Azure Databricks

### ISSUE THREAD

**Issue by saberrg** [MicrosoftLearning/mslearn-databricks#6]
Description of issue

Repro steps:

1. Webpage: https://microsoftlearning.github.io/mslearn-databricks/Instructions/Labs/03-Delta-lake-in-Azure-Databricks.html
2. In Step #7 link doesn't take you a webpage (404)

**Comment by Mihai-Ac** [comment]
Hello @saberrg 

Content sometimes goes through big updates, some also changing the structure of the content. If the link doesn´t work, please refer to the root page from where one can access all the labs for this course : [https://microsoftlearning.github.io/mslearn-databricks](https://microsoftlearning.github.io/mslearn-databricks)

For Lab 03, the correct link is [https://microsoftlearning.github.io/mslearn-databricks/Instructions/Exercises/03-Delta-lake-in-Azure-Databricks.html](https://microsoftlearning.github.io/mslearn-databricks/Instructions/Exercises/03-Delta-lake-in-Azure-Databricks.html).

Regards,
Mihai
